kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-listing-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: okteto
roleRef:
  kind: Role
  name: pod-listing-role
  apiGroup: rbac.authorization.k8s.io
